name = "myportfolio-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
account_id = "60128e897ac8700f4cc174bc06a4cfbc"

[[d1_databases]]
binding = "DB"
database_name = "myportfolio-db"
database_id = "673d66d8-1afc-451c-84fd-a0de2ca52110"

[vars]
FRONTEND_ORIGIN = "https://portfolio.federicoverdi.it"
BACKOFFICE_ORIGIN = "https://backoffice.federicoverdi.it"
CF_ZONE_ID = "90a9171402576affb201e41223313f36"
FROM_EMAIL = "io@federicoverdi.it"
NOTIFY_EMAIL = "federicoverdi@me.com"

[dev]
port = 4000
